site_name: PowerBI CLI
theme: readthedocs
repo_url: https://github.com/lgrosjean/powerbi-cli
repo_name: GitHub
edit_uri: edit/main/docs/

markdown_extensions:
  - mkdocs-click
  - toc:
      permalink: "#"
      separator: "_"
