name: mkdocs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install poetry
      - run: cp README.md docs/README.md # Necessary for poetry
      - run: poetry install --without dev
      - run: echo $OFFLINE && poetry run mkdocs gh-deploy --force
        env:
          OFFLINE: "True"
